### ISSUE TITLE
Difficulties stick / All difficulties seem too difficult

### ISSUE THREAD

**Issue by Stebulous** [Rayzr522/odyssey-interactive#2]
When i started the game i switched to hard before i started. Then switched between all of them and the game played the same. I don't know if it's just me or what.

**Comment by foxfirecodes** [comment]
The speed at which Scylla moves on hard is far faster than that of easy mode, and the pull of the whirlpool changes slightly. But the speed of Scylla is certainly noticeably different between difficulties, as well as how long Scylla’s head follows you and how fast it changes angle. 

Maybe you just weren’t paying attention, I got 100% on this project and my teacher played it for the rest of the day. He was able to notice the differences of difficulties easily :P
